apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-cluster
  name: kafka-cluster
spec:
  ports:
    - port: 9092
  selector:
    app: kafka-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-cluster
  name: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      hostname: kafka-cluster
      containers:
        - env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kafka-cluster
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_CREATE_TOPICS
            value: testing:1:1
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          name: kafka-cluster
          ports:
          - containerPort: 9092