apiVersion: v1
kind: Service
metadata:
  labels:
    service: locations
  name: locations
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: locations
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: locations
  name: locations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locations
  template:
    metadata:
      labels:
        service: locations
    spec:
      containers:
      - image: tpso/locations:latest
        name: locations
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
