apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-writer
  name: location-writer
spec:
  ports:
  - port: 5005
    targetPort: 5005
    nodePort: 30002
  selector:
    service: location-writer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-writer
  name: location-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-writer
  template:
    metadata:
      labels:
        service: location-writer
    spec:
      containers:
      - image: tpso/location-writer:latest
        name: location-writer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC
      restartPolicy: Always