---
openapi: 3.0.0
info:
  title: Connections API
  description: Find contacts
  version: 1.0.0
servers:
- url: /
paths:
  /api/persons/{personId}/connection:
    get:
      summary: Find contacts by person ID.
      description: Find contacts by person ID.
      operationId: findContacts
      parameters:
      - name: personId
        in: path
        description: ID of the person
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: start_date
        in: query
        description: Start time of the range when you want to find.
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: 2020-01-20
      - name: end_date
        in: query
        description: End time of the range when you want to find.
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: 2020-01-20
      responses:
        "200":
          description: Successfully found the person.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
        "400":
          description: Person was not found by the requested ID
components:
  schemas:
    Connection:
      type: object
      properties:
        id:
          type: integer
          format: int64
        location:
          $ref: '#/components/schemas/Connection_location'
        person:
          $ref: '#/components/schemas/Connection_person'
    Connection_location:
      type: object
      properties:
        id:
          type: integer
          format: int64
        person_id:
          type: integer
          format: int64
        longitude:
          type: integer
          format: int64
        latitude:
          type: integer
          format: int64
        creation_time:
          type: string
    Connection_person:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        company_name:
          type: string
