---
openapi: 3.0.0
info:
  title: Locations API
  description: Get location
  version: 1.0.0
servers:
- url: /
paths:
  /api/locations/{locationId}:
    get:
      summary: Get location by ID
      description: Get location by ID
      operationId: getLocationById
      parameters:
      - name: locationId
        in: path
        description: ID of the location to find
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Found location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        "404":
          description: Location was not found by the requested ID
components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int64
        person_id:
          type: integer
          format: int64
        longitude:
          type: string
        latitude:
          type: string
        creation_time:
          type: string
