---
openapi: 3.0.0
info:
  title: Persons API
  description: Create and get perons
  version: 1.0.0
servers:
- url: /
paths:
  /api/persons:
    get:
      summary: Retrieves all persons
      description: Retrieves all persons that have been created.
      operationId: getPersons
      responses:
        "200":
          description: All persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
    post:
      summary: Create new person
      description: Create new person
      operationId: createPerson
      requestBody:
        description: Person data to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        "201":
          description: Person created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
  /api/persons/{personId}:
    get:
      summary: Retrieves person by ID
      description: Retrieves person by ID.
      operationId: getPersonById
      parameters:
      - name: personId
        in: path
        description: ID of the person to find
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Person found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        "404":
          description: Requested person ID was not found.
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        company_name:
          type: string
