# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udaconnect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='udaconnect.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10udaconnect.proto\"X\n\rPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"1\n\x11GetPersonResponse\x12\x1c\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0e.PersonMessage26\n\x06Person\x12,\n\x03Get\x12\x11.GetPersonRequest\x1a\x12.GetPersonResponseb\x06proto3'
)




_PERSONMESSAGE = _descriptor.Descriptor(
  name='PersonMessage',
  full_name='PersonMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PersonMessage.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='PersonMessage.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='PersonMessage.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='company_name', full_name='PersonMessage.company_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=108,
)


_GETPERSONREQUEST = _descriptor.Descriptor(
  name='GetPersonRequest',
  full_name='GetPersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetPersonRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=140,
)


_GETPERSONRESPONSE = _descriptor.Descriptor(
  name='GetPersonResponse',
  full_name='GetPersonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='GetPersonResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=191,
)

_GETPERSONRESPONSE.fields_by_name['data'].message_type = _PERSONMESSAGE
DESCRIPTOR.message_types_by_name['PersonMessage'] = _PERSONMESSAGE
DESCRIPTOR.message_types_by_name['GetPersonRequest'] = _GETPERSONREQUEST
DESCRIPTOR.message_types_by_name['GetPersonResponse'] = _GETPERSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonMessage = _reflection.GeneratedProtocolMessageType('PersonMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMESSAGE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:PersonMessage)
  })
_sym_db.RegisterMessage(PersonMessage)

GetPersonRequest = _reflection.GeneratedProtocolMessageType('GetPersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPERSONREQUEST,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:GetPersonRequest)
  })
_sym_db.RegisterMessage(GetPersonRequest)

GetPersonResponse = _reflection.GeneratedProtocolMessageType('GetPersonResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPERSONRESPONSE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:GetPersonResponse)
  })
_sym_db.RegisterMessage(GetPersonResponse)



_PERSON = _descriptor.ServiceDescriptor(
  name='Person',
  full_name='Person',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=193,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='Person.Get',
    index=0,
    containing_service=None,
    input_type=_GETPERSONREQUEST,
    output_type=_GETPERSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSON)

DESCRIPTOR.services_by_name['Person'] = _PERSON

# @@protoc_insertion_point(module_scope)
