# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udaconnect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='udaconnect.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10udaconnect.proto\"X\n\rPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"1\n\x11GetPersonResponse\x12\x1c\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0e.PersonMessage\"6\n\x13\x43reatePersonRequest\x12\x1f\n\x07payload\x18\x01 \x01(\x0b\x32\x0e.PersonMessage\"4\n\x14\x43reatePersonResponse\x12\x1c\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0e.PersonMessage\"\x15\n\x13GetAllPersonRequest\"4\n\x14GetAllPersonResponse\x12\x1c\n\x04list\x18\x01 \x03(\x0b\x32\x0e.PersonMessage\"l\n\x0fLocationMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tperson_id\x18\x02 \x01(\x03\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\x03\" \n\x12GetLocationRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"5\n\x13GetLocationResponse\x12\x1e\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x10.LocationMessage\"W\n\x11\x43onnectionMessage\x12\"\n\x08location\x18\x01 \x01(\x0b\x32\x10.LocationMessage\x12\x1e\n\x06person\x18\x02 \x01(\x0b\x32\x0e.PersonMessage\"`\n\x13\x46indContactsRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x03\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x10\n\x08\x64istance\x18\x04 \x01(\x03\"<\n\x14\x46indContactsResponse\x12$\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x12.ConnectionMessage2\xa4\x01\n\x06Person\x12,\n\x03Get\x12\x11.GetPersonRequest\x1a\x12.GetPersonResponse\x12\x35\n\x06\x43reate\x12\x14.CreatePersonRequest\x1a\x15.CreatePersonResponse\x12\x35\n\x06GetAll\x12\x14.GetAllPersonRequest\x1a\x15.GetAllPersonResponse2<\n\x08Location\x12\x30\n\x03Get\x12\x13.GetLocationRequest\x1a\x14.GetLocationResponse2I\n\nConnection\x12;\n\x0c\x46indContacts\x12\x14.FindContactsRequest\x1a\x15.FindContactsResponseb\x06proto3'
)




_PERSONMESSAGE = _descriptor.Descriptor(
  name='PersonMessage',
  full_name='PersonMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PersonMessage.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='PersonMessage.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='PersonMessage.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='company_name', full_name='PersonMessage.company_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=108,
)


_GETPERSONREQUEST = _descriptor.Descriptor(
  name='GetPersonRequest',
  full_name='GetPersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetPersonRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=140,
)


_GETPERSONRESPONSE = _descriptor.Descriptor(
  name='GetPersonResponse',
  full_name='GetPersonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='GetPersonResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=191,
)


_CREATEPERSONREQUEST = _descriptor.Descriptor(
  name='CreatePersonRequest',
  full_name='CreatePersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='CreatePersonRequest.payload', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=247,
)


_CREATEPERSONRESPONSE = _descriptor.Descriptor(
  name='CreatePersonResponse',
  full_name='CreatePersonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='CreatePersonResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=301,
)


_GETALLPERSONREQUEST = _descriptor.Descriptor(
  name='GetAllPersonRequest',
  full_name='GetAllPersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=324,
)


_GETALLPERSONRESPONSE = _descriptor.Descriptor(
  name='GetAllPersonResponse',
  full_name='GetAllPersonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='GetAllPersonResponse.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=378,
)


_LOCATIONMESSAGE = _descriptor.Descriptor(
  name='LocationMessage',
  full_name='LocationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LocationMessage.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='person_id', full_name='LocationMessage.person_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='LocationMessage.longitude', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='LocationMessage.latitude', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='LocationMessage.creation_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=488,
)


_GETLOCATIONREQUEST = _descriptor.Descriptor(
  name='GetLocationRequest',
  full_name='GetLocationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetLocationRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=522,
)


_GETLOCATIONRESPONSE = _descriptor.Descriptor(
  name='GetLocationResponse',
  full_name='GetLocationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='GetLocationResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=577,
)


_CONNECTIONMESSAGE = _descriptor.Descriptor(
  name='ConnectionMessage',
  full_name='ConnectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='ConnectionMessage.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='person', full_name='ConnectionMessage.person', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=666,
)


_FINDCONTACTSREQUEST = _descriptor.Descriptor(
  name='FindContactsRequest',
  full_name='FindContactsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='person_id', full_name='FindContactsRequest.person_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='FindContactsRequest.start_date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='FindContactsRequest.end_date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='FindContactsRequest.distance', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=764,
)


_FINDCONTACTSRESPONSE = _descriptor.Descriptor(
  name='FindContactsResponse',
  full_name='FindContactsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contacts', full_name='FindContactsResponse.contacts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=766,
  serialized_end=826,
)

_GETPERSONRESPONSE.fields_by_name['data'].message_type = _PERSONMESSAGE
_CREATEPERSONREQUEST.fields_by_name['payload'].message_type = _PERSONMESSAGE
_CREATEPERSONRESPONSE.fields_by_name['data'].message_type = _PERSONMESSAGE
_GETALLPERSONRESPONSE.fields_by_name['list'].message_type = _PERSONMESSAGE
_GETLOCATIONRESPONSE.fields_by_name['data'].message_type = _LOCATIONMESSAGE
_CONNECTIONMESSAGE.fields_by_name['location'].message_type = _LOCATIONMESSAGE
_CONNECTIONMESSAGE.fields_by_name['person'].message_type = _PERSONMESSAGE
_FINDCONTACTSRESPONSE.fields_by_name['contacts'].message_type = _CONNECTIONMESSAGE
DESCRIPTOR.message_types_by_name['PersonMessage'] = _PERSONMESSAGE
DESCRIPTOR.message_types_by_name['GetPersonRequest'] = _GETPERSONREQUEST
DESCRIPTOR.message_types_by_name['GetPersonResponse'] = _GETPERSONRESPONSE
DESCRIPTOR.message_types_by_name['CreatePersonRequest'] = _CREATEPERSONREQUEST
DESCRIPTOR.message_types_by_name['CreatePersonResponse'] = _CREATEPERSONRESPONSE
DESCRIPTOR.message_types_by_name['GetAllPersonRequest'] = _GETALLPERSONREQUEST
DESCRIPTOR.message_types_by_name['GetAllPersonResponse'] = _GETALLPERSONRESPONSE
DESCRIPTOR.message_types_by_name['LocationMessage'] = _LOCATIONMESSAGE
DESCRIPTOR.message_types_by_name['GetLocationRequest'] = _GETLOCATIONREQUEST
DESCRIPTOR.message_types_by_name['GetLocationResponse'] = _GETLOCATIONRESPONSE
DESCRIPTOR.message_types_by_name['ConnectionMessage'] = _CONNECTIONMESSAGE
DESCRIPTOR.message_types_by_name['FindContactsRequest'] = _FINDCONTACTSREQUEST
DESCRIPTOR.message_types_by_name['FindContactsResponse'] = _FINDCONTACTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonMessage = _reflection.GeneratedProtocolMessageType('PersonMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMESSAGE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:PersonMessage)
  })
_sym_db.RegisterMessage(PersonMessage)

GetPersonRequest = _reflection.GeneratedProtocolMessageType('GetPersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPERSONREQUEST,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:GetPersonRequest)
  })
_sym_db.RegisterMessage(GetPersonRequest)

GetPersonResponse = _reflection.GeneratedProtocolMessageType('GetPersonResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPERSONRESPONSE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:GetPersonResponse)
  })
_sym_db.RegisterMessage(GetPersonResponse)

CreatePersonRequest = _reflection.GeneratedProtocolMessageType('CreatePersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPERSONREQUEST,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:CreatePersonRequest)
  })
_sym_db.RegisterMessage(CreatePersonRequest)

CreatePersonResponse = _reflection.GeneratedProtocolMessageType('CreatePersonResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPERSONRESPONSE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:CreatePersonResponse)
  })
_sym_db.RegisterMessage(CreatePersonResponse)

GetAllPersonRequest = _reflection.GeneratedProtocolMessageType('GetAllPersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLPERSONREQUEST,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:GetAllPersonRequest)
  })
_sym_db.RegisterMessage(GetAllPersonRequest)

GetAllPersonResponse = _reflection.GeneratedProtocolMessageType('GetAllPersonResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLPERSONRESPONSE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:GetAllPersonResponse)
  })
_sym_db.RegisterMessage(GetAllPersonResponse)

LocationMessage = _reflection.GeneratedProtocolMessageType('LocationMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessage)
  })
_sym_db.RegisterMessage(LocationMessage)

GetLocationRequest = _reflection.GeneratedProtocolMessageType('GetLocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLOCATIONREQUEST,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:GetLocationRequest)
  })
_sym_db.RegisterMessage(GetLocationRequest)

GetLocationResponse = _reflection.GeneratedProtocolMessageType('GetLocationResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLOCATIONRESPONSE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:GetLocationResponse)
  })
_sym_db.RegisterMessage(GetLocationResponse)

ConnectionMessage = _reflection.GeneratedProtocolMessageType('ConnectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONMESSAGE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionMessage)
  })
_sym_db.RegisterMessage(ConnectionMessage)

FindContactsRequest = _reflection.GeneratedProtocolMessageType('FindContactsRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDCONTACTSREQUEST,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:FindContactsRequest)
  })
_sym_db.RegisterMessage(FindContactsRequest)

FindContactsResponse = _reflection.GeneratedProtocolMessageType('FindContactsResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINDCONTACTSRESPONSE,
  '__module__' : 'udaconnect_pb2'
  # @@protoc_insertion_point(class_scope:FindContactsResponse)
  })
_sym_db.RegisterMessage(FindContactsResponse)



_PERSON = _descriptor.ServiceDescriptor(
  name='Person',
  full_name='Person',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=829,
  serialized_end=993,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='Person.Get',
    index=0,
    containing_service=None,
    input_type=_GETPERSONREQUEST,
    output_type=_GETPERSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='Person.Create',
    index=1,
    containing_service=None,
    input_type=_CREATEPERSONREQUEST,
    output_type=_CREATEPERSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='Person.GetAll',
    index=2,
    containing_service=None,
    input_type=_GETALLPERSONREQUEST,
    output_type=_GETALLPERSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSON)

DESCRIPTOR.services_by_name['Person'] = _PERSON


_LOCATION = _descriptor.ServiceDescriptor(
  name='Location',
  full_name='Location',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=995,
  serialized_end=1055,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='Location.Get',
    index=0,
    containing_service=None,
    input_type=_GETLOCATIONREQUEST,
    output_type=_GETLOCATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCATION)

DESCRIPTOR.services_by_name['Location'] = _LOCATION


_CONNECTION = _descriptor.ServiceDescriptor(
  name='Connection',
  full_name='Connection',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1057,
  serialized_end=1130,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindContacts',
    full_name='Connection.FindContacts',
    index=0,
    containing_service=None,
    input_type=_FINDCONTACTSREQUEST,
    output_type=_FINDCONTACTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTION)

DESCRIPTOR.services_by_name['Connection'] = _CONNECTION

# @@protoc_insertion_point(module_scope)
